repos:
  - repo: local
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        language: python
        types: [python]
        # for backward compatibility
        files: ''
        minimum_pre_commit_version: 0.15.0
        args: ['--py36-plus']
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [python]
        args: ['--line-length=79']
    -   id: flake8
        name: flake8
        description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
        entry: flake8
        language: python
        types: [python]
        additional_dependencies:
          - flake8-broken-line
          - flake8-blind-except
          - flake8-builtins
          - flake8-logging-format
          - flake8-print
#          - flake8-docstrings
#          - flake8-mypy
        args: ['--max-line-length=100',
               '--ignore=W503,E203,T001,E501,RST201,RST203,RST301,S301,S403,D212,D200,C901,E731,G004',
               '--max-complexity=10',
               '--select=B,B9,C,D,DAR,E,F,N,RST,S,W,C4']
       