site_name: Plastic Origins

theme:
  name: material

plugins:
  - mkdocstrings
  
yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - Detection: detection-reference.md
        - Serving: serving-reference.md
        - Tools: tools-reference.md
        - Tracking: tracking-reference.md
        - Training: training-reference.md

