name: Prerelease

on:
  push

jobs:
  tests:
    name: "${{ matrix.python-version }} / ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.8, os: ubuntu-latest }
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python {{ "${{ matrix.python-version }}" }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || echo ::set-output name=prerelease::true
          echo "::set-output name=tag::$(poetry version --short)"
          echo "::set-output name=branch::$(echo $GITHUB_REF | cut -d'/' -f 3)"
      - name: Print outputs 
        run: |
          echo "${{steps.check-version.outputs.branch}}"
          echo "${{steps.check-version.outputs.tag}}"
          echo "${{steps.check-version.outputs.prerelease}}"
          echo "$(poetry version --short)"
      - name: get-version
        run: |
          v=$(echo ${{steps.check-version.outputs.tag}} | cut -d'-' -f 1)
          echo "::set-output name=version::$v"
      - name: get-version2
        uses: actions/github-script@0.9.0
        with:
          script: |
            const id = steps.check-version.outputs.tag.split('-')[1]
            core.setOutput('version', id)
      - name: print version
        run: |
          echo "${{steps.get-version.outputs.version}}"
          echo "${{steps.get-version2.outputs.version}}"
        

