name: Prerelease

on:
  push

jobs:
  tests:
    name: "${{ matrix.python-version }} / ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.8, os: ubuntu-latest }
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python {{ "${{ matrix.python-version }}" }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Read bump rule
        id: bump-rule
        uses: juliangruber/read-file-action@v1
        with:
          path: bump.txt
      - name: Echo bump.txt
        run: echo "${{ steps.package.outputs.content }}"

